# Generated by Django 3.0.3 on 2020-06-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10_Chapter',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nama_chapter', models.CharField(max_length=149)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10_Kategori',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kat', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_kat', models.CharField(max_length=199)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10_Subchapter',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subchapter', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nama_subchapter', models.CharField(max_length=199)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icdD10_subchapter', to='app_BHGISv2.ICD10_Chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD10_Subkategori',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subkat', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nama_subkat', models.CharField(max_length=100)),
                ('kat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icd10_subkategori', to='app_BHGISv2.ICD10_Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indeks',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kode', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kode_kec', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_kec', models.CharField(max_length=25)),
                ('lat', models.FloatField(null=True)),
                ('longt', models.FloatField(null=True)),
                ('pddk_l', models.PositiveIntegerField()),
                ('pddk_p', models.PositiveIntegerField()),
                ('jml_pddk', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kat_pasien', models.SmallAutoField(primary_key=True, serialize=False)),
                ('umur', models.CharField(max_length=10)),
                ('jenis_kelamin', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kode_pkm', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nama_pkm', models.CharField(max_length=30)),
                ('lat', models.FloatField(null=True)),
                ('longt', models.FloatField(null=True)),
                ('kode_kec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puskesmas', to='app_BHGISv2.Kecamatan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kasus_baru', models.PositiveSmallIntegerField(blank=True)),
                ('kasus_lama', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah', models.PositiveSmallIntegerField(blank=True)),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kasus', to='app_BHGISv2.ICD10_Subkategori')),
                ('kat_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kasus', to='app_BHGISv2.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kasus', to='app_BHGISv2.Indeks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jumlah_Subchapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kasus_baru', models.PositiveIntegerField(blank=True)),
                ('kasus_lama', models.PositiveIntegerField(blank=True)),
                ('jumlah', models.PositiveIntegerField(blank=True)),
                ('kat_pasien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_subchapter', to='app_BHGISv2.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_subchapter', to='app_BHGISv2.Indeks')),
                ('subchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_subchapter', to='app_BHGISv2.ICD10_Subchapter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jumlah_Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kasus_lama', models.PositiveIntegerField(blank=True)),
                ('kasus_baru', models.PositiveIntegerField(blank=True)),
                ('jumlah', models.PositiveIntegerField(blank=True)),
                ('kat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_kategori', to='app_BHGISv2.ICD10_Kategori')),
                ('kat_pasien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_kategori', to='app_BHGISv2.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_kategori', to='app_BHGISv2.Indeks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jumlah_Kasus_Subkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jumlah_baru_l', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah_baru_p', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah_lama_l', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah_lama_p', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah', models.PositiveSmallIntegerField(blank=True)),
                ('gakin', models.PositiveSmallIntegerField(blank=True)),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jumlah_Kasus_subkat', to='app_BHGISv2.ICD10_Subkategori')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jumlah_Kasus_subkat', to='app_BHGISv2.Indeks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jumlah_Kasus_Kat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jumlah_baru_l', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah_baru_p', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah_lama_l', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah_lama_p', models.PositiveSmallIntegerField(blank=True)),
                ('jumlah', models.PositiveSmallIntegerField(blank=True)),
                ('gakin', models.PositiveSmallIntegerField(blank=True)),
                ('kat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_kasus_kat', to='app_BHGISv2.ICD10_Kategori')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_kasus_kat', to='app_BHGISv2.Indeks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jumlah_Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kasus_baru', models.PositiveIntegerField(blank=True)),
                ('kasus_lama', models.PositiveIntegerField(blank=True)),
                ('jumlah', models.PositiveIntegerField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_chapter', to='app_BHGISv2.ICD10_Chapter')),
                ('kat_pasien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_chapter', to='app_BHGISv2.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_chapter', to='app_BHGISv2.Indeks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indeks',
            name='kode_pkm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indeks', to='app_BHGISv2.Puskesmas'),
        ),
        migrations.AddField(
            model_name='icd10_kategori',
            name='subchapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icd10_kategori', to='app_BHGISv2.ICD10_Subchapter'),
        ),
    ]
