# Generated by Django 3.0.3 on 2020-06-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_BHGISv2', '0002_remove_indeks_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumlah_chapter',
            old_name='jumlah_chapter',
            new_name='jumlah',
        ),
        migrations.RenameField(
            model_name='jumlah_chapter',
            old_name='jumlah_chapter_baru',
            new_name='kasus_baru',
        ),
        migrations.RenameField(
            model_name='jumlah_chapter',
            old_name='jumlah_chapter_lama',
            new_name='kasus_lama',
        ),
        migrations.RenameField(
            model_name='jumlah_kategori',
            old_name='jumlah_kat',
            new_name='jumlah',
        ),
        migrations.RenameField(
            model_name='jumlah_kategori',
            old_name='jumlah_kat_baru',
            new_name='kasus_baru',
        ),
        migrations.RenameField(
            model_name='jumlah_kategori',
            old_name='jumlah_kat_lama',
            new_name='kasus_lama',
        ),
        migrations.RenameField(
            model_name='jumlah_subchapter',
            old_name='jumlah_subchapter',
            new_name='jumlah',
        ),
        migrations.RenameField(
            model_name='jumlah_subchapter',
            old_name='jumlah_subchapter_baru',
            new_name='kasus_baru',
        ),
        migrations.RenameField(
            model_name='jumlah_subchapter',
            old_name='jumlah_subchapter_lama',
            new_name='kasus_lama',
        ),
        migrations.RenameField(
            model_name='kecamatan',
            old_name='lat_kec',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='kecamatan',
            old_name='longt_kec',
            new_name='longt',
        ),
        migrations.RenameField(
            model_name='puskesmas',
            old_name='lat_pkm',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='puskesmas',
            old_name='longt_pkm',
            new_name='longt',
        ),
        migrations.AddField(
            model_name='kasus',
            name='jumlah',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
