# Generated by Django 3.0.3 on 2020-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_BHGISv2', '0002_auto_20200621_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='klaster_penyakit',
            name='ekspektasi_kasus',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klaster_penyakit',
            name='jumlah_populasi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klaster_penyakit',
            name='p_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klaster_penyakit',
            name='rank',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klaster_penyakit',
            name='smr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klaster_penyakit',
            name='jumlah_kasus',
            field=models.PositiveIntegerField(),
        ),
    ]
